"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { Check, GitBranch, UserRound, Link2 } from "lucide-react";
import { useFamily } from "@/components/family-provider";
import { connectedPeople, initials, lifespan, type Request } from "@/lib/family";
import { Empty, PageHeading } from "./workspace";

function RequestList({ kind }: { kind: Request["kind"] }) {
  const { state } = useFamily(); const requests = state.requests.filter(r => r.kind === kind);
  return <div className="ft-request-list">{requests.map(r => <div key={r.id}><strong>{state.people.find(p => p.id === r.personId)?.name}</strong><p>{r.detail}</p><span className="ft-badge">{r.status}</span></div>)}</div>;
}
export function ConnectionsPage() {
  const { state, update } = useFamily(); const people = connectedPeople(state);
  const [personId, setPersonId] = useState(people.find(p => !p.living)?.id ?? people[0]?.id ?? ""); const [message, setMessage] = useState("");
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const element = e.currentTarget; const form = new FormData(element); const reference = String(form.get("reference")).trim(); const evidence = String(form.get("evidence")).trim(); if (!reference || !evidence) return;
    if (await update(s => ({ ...s, requests: [...s.requests, { id: crypto.randomUUID(), kind: "Connection", personId, detail: `Other profile: ${reference}. Evidence: ${evidence}`, status: "Pending review", created: new Date().toISOString() }] }))) { setMessage("Connection request saved to your tree. No profiles have been merged."); element.reset(); }
  }
  return <div className="ft-page"><PageHeading eyebrow="Where branches meet" title="Connect through family" description="A shared ancestor can connect two people’s views of the same family." /><div className="ft-connection-illustration" aria-label="Two personal trees connected through one shared ancestor"><span><UserRound />Your view</span><i /><span><GitBranch />Shared ancestor</span><i /><span><UserRound />Their view</span></div><div className="ft-columns"><section className="ft-paper"><h2>Suggest a shared person</h2><form className="ft-form" onSubmit={submit}><label>Person in your tree<select value={personId} onChange={e => setPersonId(e.target.value)}>{people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Other person’s profile link or ID<input required name="reference" placeholder="Profile reference from your relative" /></label><label>What tells you they are the same person?<textarea name="evidence" required placeholder="Dates, parents, places, or a shared family record" /></label><button className="button button-primary"><Link2 size={16} /> Save connection request</button></form>{message && <p className="ft-note" role="status">{message}</p>}</section><aside className="ft-side-note"><span className="ft-kicker">Before a connection is confirmed</span><h2>Names alone aren’t enough.</h2><p>Compare dates, parents, and sources together. Conflicting details stay visible for family review.</p><ol><li>Identify the shared person.</li><li>Ask both sides to review.</li><li>Connect the records while preserving contributions.</li></ol><p>Cross-account matching and confirmation will become available when accounts are connected.</p></aside></div><div className="ft-section-title"><h2>Connection requests</h2></div><RequestList kind="Connection" /></div>;
}
export function SetupPage({ claimId }: { claimId?: string }) {
  const { state, update } = useFamily(); const [selected, setSelected] = useState(claimId ?? ""); const [message, setMessage] = useState("");
  const candidates = state.people.filter(p => p.living && !p.accountId);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget);
    if (await update(s => { const target = s.people.find(p => p.id === selected); if (!target?.living || target.accountId) throw new Error("Only living, unclaimed profiles can be requested."); return { ...s, requests: [...s.requests, { id: crypto.randomUUID(), kind: "Claim", personId: selected, detail: String(data.get("evidence")).trim(), status: "Pending review", created: new Date().toISOString() }] }; })) setMessage("Claim request saved to your tree for review. The profile remains unclaimed until identity is verified.");
  }
  if (!claimId) return <div className="ft-page ft-narrow"><PageHeading eyebrow="Your place in the family" title="Your profile is already here" description="Your signed-in account is the first member of your personal tree." /><section className="ft-paper"><p className="ft-note">Add parents, partners, children, and the people whose stories you want to preserve.</p><Link className="button button-primary" href="/tree">Open my tree</Link></section></div>;
  return <div className="ft-page ft-narrow"><PageHeading eyebrow="Claim a living profile" title="Find your place in the family" description="Request to connect your account to an existing profile." /><section className="ft-paper"><form className="ft-form" onSubmit={submit}><label>Living, unclaimed profile<select required value={selected} onChange={e => setSelected(e.target.value)}><option value="">Choose a profile</option>{candidates.map(p => <option key={p.id} value={p.id}>{p.name} · {lifespan(p)}</option>)}</select></label><label>Help family confirm your identity<textarea required name="evidence" placeholder="Explain your connection. Do not include identity documents here." /></label><p className="ft-note">A claim request does not grant access or replace family-written biographies.</p><button className="button button-primary" disabled={!selected}>Request this profile</button></form>{message && <p role="status" className="ft-note">{message}</p>}</section><RequestList kind="Claim" /></div>;
}
export function SettingsPage() {
  const { state, update } = useFamily(); const viewer = state.people.find(p => p.id === state.viewerId)!; const [message, setMessage] = useState("");
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const name = String(data.get("name")).trim(); if (!name) return;
    if (await update(s => ({ ...s, people: s.people.map(p => p.id === s.viewerId ? { ...p, name, born: String(data.get("born")) } : p), settings: { email: String(data.get("email")), reviewNotifications: data.has("notifications"), discoverable: data.has("discoverable") } }))) setMessage("Preferences saved to your tree.");
  }
  function download() { const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "familytree.json"; a.click(); URL.revokeObjectURL(url); }
  return <div className="ft-page ft-narrow"><PageHeading eyebrow="Personal account" title="Your details" description="Your identity and preferences. Your biography belongs to the people who know you." /><section className="ft-paper"><form className="ft-form" onSubmit={save}><label>Name<input name="name" required defaultValue={viewer.name} /></label><label>Email<input name="email" type="email" readOnly defaultValue={state.settings.email} /></label><label>Birth date or year<input name="born" maxLength={10} placeholder="YYYY-MM-DD or YYYY" defaultValue={viewer.born} /></label><label className="ft-check"><input type="checkbox" name="notifications" defaultChecked={state.settings.reviewNotifications} /> Notify me about family reviews</label><label className="ft-check"><input type="checkbox" name="discoverable" defaultChecked={state.settings.discoverable} /> Allow future shared-ancestor suggestions</label><p className="ft-muted">Preferences are saved to your tree; email delivery and discovery are not connected yet.</p><button className="button button-primary">Save changes</button></form>{message && <p role="status">{message}</p>}</section><section className="ft-paper"><h2>Your contributions, kept close</h2><p>Download a copy of your family data.</p><button className="button button-secondary" onClick={download}>Export family data</button><p><Link className="ft-text-button" href="/auth/forgot-password">Password recovery →</Link></p><p><Link className="ft-text-button" href="/auth/verify-email">Email verification →</Link></p></section></div>;
}
