"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Check, GitBranch, UserRound, Link2 } from "lucide-react";
import { useFamily } from "@/components/family-provider";
import { connectedPeople, initials, lifespan, type Request } from "@/lib/family";
import { Empty, PageHeading } from "./workspace";

function RequestList({ kind }: { kind: Request["kind"] }) {
  const { state } = useFamily(); const requests = state.requests.filter(r => r.kind === kind);
  return <div className="ft-request-list">{requests.map(r => <div key={r.id}><strong>{state.people.find(p => p.id === r.personId)?.name}</strong><p>{r.detail}</p><span className="ft-badge">{r.status}</span></div>)}</div>;
}
export function InvitationsPage({ personId }: { personId?: string }) {
  const { state, update } = useFamily(); const people = connectedPeople(state).filter(p => p.living && p.id !== state.viewerId && !p.accountId);
  const [selected, setSelected] = useState(people.some(p => p.id === personId) ? personId! : people[0]?.id ?? ""); const [prepared, setPrepared] = useState("");
  function prepare(e: FormEvent) { e.preventDefault(); const person = state.people.find(p => p.id === selected); if (!person) return;
    const viewer = state.people.find(p => p.id === state.viewerId)!;
    const text = `${viewer.name} would like you to join FamilyTree. A profile for ${person.name} is already connected to our family. You can request to claim it when you join. Your biography will still be written by relatives.`;
    if (update(s => ({ ...s, requests: [...s.requests, { id: crypto.randomUUID(), kind: "Invitation", personId: selected, detail: text, status: "Prepared", created: new Date().toISOString() }] }))) setPrepared(text);
  }
  return <div className="ft-page"><PageHeading eyebrow="Make the connection" title="Invite a relative" description="Help someone find their place in the family." /><div className="ft-columns"><section className="ft-paper">{people.length ? <form className="ft-form" onSubmit={prepare}><label>Who are you inviting?<select value={selected} onChange={e => { setSelected(e.target.value); setPrepared(""); }}>{people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p>They will join with their own account and can request to claim the existing profile.</p><button className="button button-primary">Prepare invitation</button></form> : <Empty title="No unclaimed living profiles"><Link href="/tree">Add a relative first →</Link></Empty>}{prepared && <div className="ft-note" role="status"><h3>Your invitation</h3><p>{prepared}</p><p>Prepared locally. No invitation has been sent.</p><button className="ft-text-button" onClick={() => { setPrepared(""); }}>Prepare another</button></div>}</section><aside className="ft-side-note"><UserRound size={26} strokeWidth={1.3} /><h2>One person. One profile.</h2><p>Joining does not duplicate a person or give them authorship of their own biography.</p><p>Claim requests need identity checks and family review before an account is connected.</p></aside></div><div className="ft-section-title"><h2>Prepared invitations</h2></div><RequestList kind="Invitation" /></div>;
}
export function ConnectionsPage() {
  const { state, update } = useFamily(); const people = connectedPeople(state);
  const [personId, setPersonId] = useState(people.find(p => !p.living)?.id ?? people[0]?.id ?? ""); const [message, setMessage] = useState("");
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const reference = String(form.get("reference")).trim(); const evidence = String(form.get("evidence")).trim(); if (!reference || !evidence) return;
    if (update(s => ({ ...s, requests: [...s.requests, { id: crypto.randomUUID(), kind: "Connection", personId, detail: `Other profile: ${reference}. Evidence: ${evidence}`, status: "Pending review", created: new Date().toISOString() }] }))) { setMessage("Connection request saved to your tree. No profiles have been merged."); e.currentTarget.reset(); }
  }
  return <div className="ft-page"><PageHeading eyebrow="Where branches meet" title="Connect through family" description="A shared ancestor can connect two people’s views of the same family." /><div className="ft-connection-illustration" aria-label="Two personal trees connected through one shared ancestor"><span><UserRound />Your view</span><i /><span><GitBranch />Shared ancestor</span><i /><span><UserRound />Their view</span></div><div className="ft-columns"><section className="ft-paper"><h2>Suggest a shared person</h2><form className="ft-form" onSubmit={submit}><label>Person in your tree<select value={personId} onChange={e => setPersonId(e.target.value)}>{people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Other person’s profile link or ID<input required name="reference" placeholder="Profile reference from your relative" /></label><label>What tells you they are the same person?<textarea name="evidence" required placeholder="Dates, parents, places, or a shared family record" /></label><button className="button button-primary"><Link2 size={16} /> Save connection request</button></form>{message && <p className="ft-note" role="status">{message}</p>}</section><aside className="ft-side-note"><span className="ft-kicker">Before a connection is confirmed</span><h2>Names alone aren’t enough.</h2><p>Compare dates, parents, and sources together. Conflicting details stay visible for family review.</p><ol><li>Identify the shared person.</li><li>Ask both sides to review.</li><li>Connect the records while preserving contributions.</li></ol><p>Cross-account matching and confirmation will become available when accounts are connected.</p></aside></div><div className="ft-section-title"><h2>Connection requests</h2></div><RequestList kind="Connection" /></div>;
}
export function SetupPage({ claimId }: { claimId?: string }) {
  const { state, update } = useFamily(); const router = useRouter(); const [mode, setMode] = useState(claimId ? "claim" : "new"); const [selected, setSelected] = useState(claimId ?? ""); const [message, setMessage] = useState("");
  const candidates = state.people.filter(p => p.living && !p.accountId);
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget);
    if (mode === "claim") { if (update(s => { const target = s.people.find(p => p.id === selected); if (!target?.living || target.accountId) throw new Error("Only living, unclaimed profiles can be requested."); return { ...s, requests: [...s.requests, { id: crypto.randomUUID(), kind: "Claim", personId: selected, detail: String(data.get("evidence")).trim(), status: "Pending review", created: new Date().toISOString() }] }; })) setMessage("Claim request saved to your tree for review. The profile remains unclaimed until identity is verified."); return; }
    const name = String(data.get("name")).trim(); if (!name) return; const id = crypto.randomUUID();
    if (update(s => ({ ...s, viewerId: id, people: [...s.people, { id, name, born: String(data.get("born")), living: true, accountId: `account-${id}`, biography: "" }], settings: { ...s.settings, email: String(data.get("email")) } }))) router.push("/tree");
  }
  return <div className="ft-page ft-narrow"><PageHeading eyebrow="Your place in the family" title="Start with you" description="Your tree begins at your profile. Relatives will tell your story." /><div className="ft-tabs"><button aria-pressed={mode === "new"} onClick={() => { setMode("new"); setMessage(""); }}>Create my profile</button><button aria-pressed={mode === "claim"} onClick={() => { setMode("claim"); setMessage(""); }}>Find an existing profile</button></div><section className="ft-paper"><form className="ft-form" onSubmit={submit}>{mode === "new" ? <><label>Your name<input name="name" autoComplete="name" required maxLength={100} /></label><label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Birth year <small>optional</small><input type="number" name="born" min="1900" max={new Date().getFullYear()} /></label><p className="ft-note">No biography needed. Add your parents next, or invite someone who knows your family.</p><button className="button button-primary">Start my tree</button></> : <><label>Living, unclaimed profile<select required value={selected} onChange={e => setSelected(e.target.value)}><option value="">Choose a profile</option>{candidates.map(p => <option key={p.id} value={p.id}>{p.name} · {lifespan(p)}</option>)}</select></label><label>Help family confirm your identity<textarea required name="evidence" placeholder="Explain your connection. Do not include identity documents here." /></label><p className="ft-note">A claim request does not grant access or replace family-written biographies.</p><button className="button button-primary" disabled={!selected}>Request this profile</button></>}</form>{message && <p role="status" className="ft-note">{message}</p>}</section><RequestList kind="Claim" /></div>;
}
export function SettingsPage() {
  const { state, update } = useFamily(); const viewer = state.people.find(p => p.id === state.viewerId)!; const [message, setMessage] = useState("");
  function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); const name = String(data.get("name")).trim(); if (!name) return;
    if (update(s => ({ ...s, people: s.people.map(p => p.id === s.viewerId ? { ...p, name, born: String(data.get("born")) } : p), settings: { email: String(data.get("email")), reviewNotifications: data.has("notifications"), discoverable: data.has("discoverable") } }))) setMessage("Preferences saved to your tree.");
  }
  function download() { const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "familytree.json"; a.click(); URL.revokeObjectURL(url); }
  return <div className="ft-page ft-narrow"><PageHeading eyebrow="Personal account" title="Your details" description="Your identity and preferences. Your biography belongs to the people who know you." /><section className="ft-paper"><form className="ft-form" onSubmit={save}><label>Name<input name="name" required defaultValue={viewer.name} /></label><label>Email<input name="email" type="email" required defaultValue={state.settings.email} /></label><label>Birth year<input name="born" type="number" min="1900" max={new Date().getFullYear()} defaultValue={viewer.born} /></label><label className="ft-check"><input type="checkbox" name="notifications" defaultChecked={state.settings.reviewNotifications} /> Notify me about family reviews</label><label className="ft-check"><input type="checkbox" name="discoverable" defaultChecked={state.settings.discoverable} /> Allow future shared-ancestor suggestions</label><p className="ft-muted">Preferences are saved locally; email delivery and discovery are not connected yet.</p><button className="button button-primary">Save changes</button></form>{message && <p role="status">{message}</p>}</section><section className="ft-paper"><h2>Your contributions, kept close</h2><p>Download the family data saved in this browser.</p><button className="button button-secondary" onClick={download}>Export family data</button><p><Link className="ft-text-button" href="/auth/forgot-password">Password recovery →</Link></p><p><Link className="ft-text-button" href="/auth/verify-email">Email verification →</Link></p></section></div>;
}
